version: '3.8'
services:
  app:
    image: php:8.1-fpm
    build:
      context: ./docker
      dockerfile: Dockerfile
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www
  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - 8881:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
volumes:
  data:
